site_name: Documentation for OpenWindMap API v1
site_url: http://developers.pioupiou.fr
site_description: Documentation for OpenWindMap API v1
site_author: OpenWindMap

repo_url: https://github.com/OpenWindMap/api-v1-doc

nav:
- Home: index.md
- API:
  - Live: api/live/index.md
  - Archive: api/archive/index.md
#  - Edit: test.md
  - Push: api/push/index.md
#- Widgets:
#  - Live:
#    - Live: test.md
#  - Archive: test.md
#  - Edit: test.md
#  - Push: test.md
- Licensing : data-licensing.md
- More:
  - Get support: support.md
#  - Usage policy: usage-policy.md
#  - Service status: http://status.pioupiou.fr
  - Bug tracker: bug-tracker.md
  - Contribute: contribute.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition:
  
copyright: Copyright &copy; 2015 Bac Plus Zéro SAS, &copy; 2021-2023 OpenWindMap SCIC SA - This documentation is licensed under  <a href="http://creativecommons.org/licenses/by/4.0/" target="_blank">CC-By 4.0</a>.
